# papigoplug-test.yaml

name: papigoplug-test

on:
  push:
    branches: [main, development, tests]
  pull_request:
  workflow_dispatch:

jobs:
  papigoplug-test-bookworm:
    runs-on: golang:1.21.4-bookworm

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run Tests
        run: go test -v ./papigoplug_test/papigoplug_test.go
